# Generated by Django 3.0.6 on 2020-08-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
