# Generated by Django 3.0.6 on 2020-08-10 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_is_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='year',
        ),
    ]
